version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - otp-network

  app1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - THROTTLE_TTL=5000
      - THROTTLE_LIMIT=1
      - PORT=3000
    depends_on:
      - redis
    networks:
      - otp-network

  app2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - THROTTLE_TTL=1000
      - THROTTLE_LIMIT=1
      - PORT=3000
    depends_on:
      - redis
    networks:
      - otp-network

  app3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - THROTTLE_TTL=10000
      - THROTTLE_LIMIT=3
      - PORT=3000
    depends_on:
      - redis
    networks:
      - otp-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge

volumes:
  redis-data: